{{- if .Values.entities.data }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nanomask.fullname" . }}-entities
  labels:
    {{- include "nanomask.labels" . | nindent 4 }}
data:
  entities.txt: |
    {{- .Values.entities.data | nindent 4 }}
{{- end }}
