{{- if .Values.tls.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nanomask.fullname" . }}-tls
  labels:
    {{- include "nanomask.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certData | quote }}
  tls.key: {{ .Values.tls.keyData | quote }}
  {{- if .Values.tls.caData }}
  ca.crt: {{ .Values.tls.caData | quote }}
  {{- end }}
{{- end }}
