{{- if and .Values.hashing.key .Values.hashing.fileData }}
{{- fail "Set only one of hashing.key or hashing.fileData" }}
{{- end }}
{{- if or .Values.hashing.key .Values.hashing.fileData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nanomask.fullname" . }}-hashing
  labels:
    {{- include "nanomask.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.hashing.key }}
  hash-key: {{ .Values.hashing.key | quote }}
  {{- end }}
  {{- if .Values.hashing.fileData }}
  {{ .Values.hashing.fileName }}: |
    {{- .Values.hashing.fileData | nindent 4 }}
  {{- end }}
{{- end }}
