{{- if .Values.adminApi.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nanomask.fullname" . }}-admin
  labels:
    {{- include "nanomask.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.adminApi.token | b64enc | quote }}
{{- end }}
